# Generated by Django 5.2.4 on 2025-07-21 11:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_products_photo_alter_products_purchase_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='photo',
            field=models.ImageField(blank=True, default='no_photo.png', null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='purchase_date',
            field=models.DateField(blank=True, default=datetime.date(2025, 7, 21), null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='supplier',
            field=models.IntegerField(blank=True, choices=[(17, 'Supplier_1')], null=True),
        ),
    ]
