# Generated by Django 5.2.4 on 2025-07-21 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_products_supplier'),
        ('supplier', '0002_alter_suppliers_phone_alter_suppliers_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplier.suppliers'),
        ),
    ]
