# Generated by Django 5.2.4 on 2025-07-23 21:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_products_purchase_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='designation',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='purchase_date',
            field=models.DateField(blank=True, default=datetime.date(2025, 7, 23), null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='reference',
            field=models.CharField(max_length=20),
        ),
    ]
