# Generated by Django 5.2.4 on 2025-08-03 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_usercustomerorder_customer_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercustomerorder',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='usercustomerorder',
            name='customer_phone',
        ),
    ]
