# Generated by Django 5.2.4 on 2025-08-03 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_usercustomerorder_customer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustomer',
            name='customer_phone',
            field=models.CharField(unique=True),
        ),
    ]
