# Generated by Django 5.2.4 on 2025-07-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliers',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='photo',
            field=models.ImageField(blank=True, default='no_photo.png', null=True, upload_to='suppliers/'),
        ),
    ]
