# Generated by Django 5.2.4 on 2025-07-29 13:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_products_bare_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='purchase_date',
            field=models.DateField(blank=True, default=datetime.date(2025, 7, 29), null=True),
        ),
    ]
