# Generated by Django 5.2.4 on 2025-07-30 16:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_products_purchase_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='products',
            name='purchase_date',
            field=models.DateField(blank=True, default=datetime.date(2025, 7, 30), null=True),
        ),
    ]
