# Generated by Django 5.2.4 on 2025-07-31 16:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_products_purchase_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='purchase_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
