# Generated by Django 5.2.4 on 2025-08-02 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_usercustomerorder_amount_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustomerorder',
            name='customer_exist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='existant_costumer', to='accounts.usercustomer'),
        ),
        migrations.AlterField(
            model_name='usercustomerorder',
            name='type',
            field=models.CharField(default='Customer_Order'),
        ),
        migrations.AlterField(
            model_name='usershoporder',
            name='type',
            field=models.CharField(default='Shop_Order'),
        ),
    ]
