# Generated by Django 5.2.4 on 2025-08-03 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_usercustomerorder_customer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustomerorder',
            name='customer_name',
            field=models.CharField(default='COSTOMER'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usercustomerorder',
            name='customer_phone',
            field=models.CharField(default='PHONE'),
            preserve_default=False,
        ),
    ]
