# Generated by Django 5.2.4 on 2025-07-30 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_saleitem_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='is_closer',
            field=models.BooleanField(default=False),
        ),
    ]
