# Generated by Django 5.2.4 on 2025-07-21 23:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_categories_alter_products_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='purchase_date',
            field=models.DateField(blank=True, default=datetime.date(2025, 7, 22), null=True),
        ),
    ]
