# Generated by Django 5.2.4 on 2025-07-30 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_sale_date_alter_saleitem_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
