# Generated by Django 5.2.4 on 2025-07-31 13:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_products_category_alter_products_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='purchase_date',
            field=models.DateField(blank=True, default=datetime.date(2025, 7, 31), null=True),
        ),
    ]
