# Generated by Django 5.2.4 on 2025-07-31 16:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='Customer')),
                ('customer_name', models.CharField()),
                ('customer_phone', models.CharField()),
                ('body', models.CharField(blank=True, null=True)),
                ('date_create', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserCustomerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='Customer Order')),
                ('customer_name', models.CharField()),
                ('customer_phone', models.CharField()),
                ('product_order', models.CharField()),
                ('is_paid', models.BooleanField(default=False)),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=10, max_digits=10, null=True)),
                ('body', models.CharField(blank=True, null=True)),
                ('date_create', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('is_done', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_customer_order', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='Note')),
                ('body', models.CharField()),
                ('date_create', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('is_done', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_note', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserShopOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='Shop Order')),
                ('order_date', models.DateField(blank=True, null=True)),
                ('prod_order_name', models.CharField()),
                ('prod_order_qty', models.IntegerField(blank=True, null=True)),
                ('body', models.CharField(blank=True, null=True)),
                ('date_create', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('is_done', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_order', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
