# Generated by Django 5.2.4 on 2025-07-18 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('bare_code', models.IntegerField(max_length=20)),
                ('reference', models.CharField(max_length=10)),
                ('quantity', models.IntegerField(max_length=10)),
                ('designation', models.TextField(max_length=100)),
                ('photo', models.ImageField(upload_to='photos/%y/%m/%d')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
