# Generated by Django 5.2.4 on 2025-07-21 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_products_photo_alter_products_purchase_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='supplier',
            field=models.CharField(blank=True, choices=[('18', 'Supplier_1')], null=True),
        ),
    ]
