# Generated by Django 5.2.4 on 2025-07-19 00:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_products_options_products_purchase_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='photo',
            field=models.ImageField(blank=True, default='media/no_photo.jpg', null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='products',
            name='purchase_date',
            field=models.DateField(blank=True, default=datetime.date(2025, 7, 19), null=True),
        ),
    ]
