# Generated by Django 5.2.4 on 2025-07-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=11, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('photo', models.ImageField(blank=True, default='media/no_photo.jpg', null=True, upload_to='media')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Supplier',
            },
        ),
    ]
