# Generated by Django 5.2.4 on 2025-08-03 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_usercustomerorder_quantity_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercustomerorder',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='usercustomerorder',
            name='customer_phone',
        ),
    ]
