# Generated by Django 5.2.4 on 2025-07-18 22:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_products_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Product'},
        ),
        migrations.AddField(
            model_name='products',
            name='purchase_date',
            field=models.DateField(blank=True, default=datetime.date(2025, 7, 18), null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='supplier',
            field=models.CharField(blank=True, choices=[('SUPPLIER_1', 'SUPPLIER_1'), ('SUPPLIER_2', 'SUPPLIER_2'), ('SUPPLIER_3', 'SUPPLIER_3'), ('SUPPLIER_4', 'SUPPLIER_4')], null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='bare_code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('CONSOLE', 'CONSOLE'), ('PS5 ACCESSORIES', 'PS5 ACCESSORIES'), ('PS4 ACCESSORIES', 'PS4 ACCESSORIES'), ('NINTENDO SWITCH ACCESSORIES', 'NINTENDO SWITCH ACCESSORIES'), ('NINTENDO SWITCH2 ACCESSORIES', 'NINTENDO SWITCH ACCESSORIES'), ('JOUETS ENFANTS', 'JOUETS ENFANTS'), ('PS5 GAMES', 'PS5 GAMES'), ('PS4 GAMES', 'PS4 GAMES'), ('NINTENDO SWITCH GAMES', 'NINTENDO SWITCH GAMES'), ('NINTENDO SWITCH2 GAMES', 'NINTENDO SWITCH GAMES'), ('PHONE ACCESSORIES', 'PHONE ACCESSORIES'), ('OTHER', 'OTHER')]),
        ),
        migrations.AlterField(
            model_name='products',
            name='photo',
            field=models.ImageField(blank=True, default='phtos/25/07/18/no_photo.jpg', null=True, upload_to='photos/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.IntegerField(),
        ),
    ]
