# Generated by Django 5.2.4 on 2025-08-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_usercustomerorder_customer_exist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustomerorder',
            name='quantity_order',
            field=models.IntegerField(default=1),
        ),
    ]
