# Generated by Django 5.2.4 on 2025-07-25 18:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_products_designation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='bare_code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='purchase_date',
            field=models.DateField(blank=True, default=datetime.date(2025, 7, 25), null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='reference',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
