# Generated by Django 5.2.4 on 2025-07-30 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_saleitem_is_closer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saleitem',
            old_name='is_closer',
            new_name='is_closed',
        ),
    ]
