# Generated by Django 5.2.4 on 2025-07-31 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercustomer',
            options={'verbose_name': 'Customer'},
        ),
        migrations.AlterModelOptions(
            name='usercustomerorder',
            options={'verbose_name': 'Customer Order'},
        ),
        migrations.AlterModelOptions(
            name='usernote',
            options={'verbose_name': 'Note'},
        ),
        migrations.AlterModelOptions(
            name='usershoporder',
            options={'verbose_name': 'Shop order'},
        ),
        migrations.AddField(
            model_name='usercustomerorder',
            name='order_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usercustomer',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usercustomerorder',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usernote',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='usershoporder',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
