# Generated by Django 5.2.4 on 2025-07-31 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_usercustomer_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustomerorder',
            name='amount_paid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
