# Generated by Django 5.2.4 on 2025-07-31 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_rename_is_closer_saleitem_is_closed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleitem',
            name='is_closed',
        ),
        migrations.AddField(
            model_name='sale',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
