# Generated by Django 5.2.4 on 2025-08-08 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_products_purchase_date_alter_products_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
